import Head from 'next/head';
import Image from 'next/image';

// Types
import type { NextPage } from "next";

import { MarketingLayout } from '../layouts';

const Home: NextPage = () => {
  return (
    <MarketingLayout>
      <Head>
        <title>Welcome @ speedback</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Landingpage
      </main>
    </MarketingLayout>
  )
}

export default Home;
