import Head from 'next/head';
import Link from 'next/link';
import type { NextPage } from "next";

import { Heading, EmptyState } from '../components';
import { PlatformLayout } from '../layouts';
import { PlusIcon, EyeIcon } from '@heroicons/react/outline';

const AppProjects: NextPage = () => {
  return (
    <PlatformLayout>
      <Head>
        <title>My dashboard - speedback</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading title="My dashboard" stats={{
          commentCount: 53,
          lastCommentDate: new Date(),
        }}>
        <div className="-my-1.5 -mx-2 mt-5 flex flex-wrap lg:mt-0">
          <Link
            href="/projects"
          >
            <a className="my-1.5 mx-2 inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
              <EyeIcon className="-ml-1 mr-2 h-5 w-5" aria-hidden="true" />
              View projects
            </a>
          </Link>
          <button
            type="button"
            className="my-1.5 mx-2 inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
          >
            <PlusIcon className="-ml-1 mr-2 h-5 w-5" aria-hidden="true" />
            Start a new project
          </button>
        </div>
        </Heading>

        <EmptyState title="You have no projects. Make a new one to start gathering feedback from your customers." icon="CollectionIcon">
        <button
            type="button"
            className="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
          >
            <PlusIcon className="-ml-1 mr-2 h-5 w-5" aria-hidden="true" />
            Start a new project
          </button>
        </EmptyState>
      </main>
    </PlatformLayout>
  )
}

export default AppProjects;
