import Head from 'next/head';

// Types
import type { NextPage } from "next";

import { Heading } from '../components';

import { PlatformLayout } from '../layouts';
import { PlusIcon } from '@heroicons/react/outline';

const AppProjects: NextPage = () => {
  return (
    <PlatformLayout>
      <Head>
        <title>Projects - speedback</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading title="Projects">
        <div className="-my-1.5 -mx-2 mt-5 flex flex-wrap lg:mt-0">
          <button
            type="button"
            className="my-1.5 mx-2 inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
          >
            <PlusIcon className="-ml-1 mr-2 h-5 w-5" aria-hidden="true" />
            Start a new project
          </button>
        </div>
        </Heading>
      </main>
    </PlatformLayout>
  )
}

export default AppProjects;
